### ISSUE TITLE
download links for thorium

### ISSUE THREAD

**Issue by couleurm** [Alex313031/Alex313031.github.io#11]
i think the main homepage needs some links towards thorium releases/thorium-win, took my nerd brain a minute 👍

something like the following would be intuitive to me, make of this what you will

# Installation/Auto-UpdateHard Drive Icon

The repo can be used on any distribution that supports .deb packaging.
It is located at https://dl.thorium.rocks/.

using apt:
```
wget https://dl.thorium.rocks/debian/dists/stable/thorium.list
sudo mv thorium.list /etc/apt/sources.list.d/
sudo apt update
sudo apt install thorium-browser
```
For btw users [some builds are present on the AUR](https://aur.archlinux.org/packages?O=0&K=thorium)

* [Linux builds](https://github.com/Alex313031/thorium)
* [Windows 10/11 builds](https://github.com/Alex313031/thorium-win)
* [Windows 7 builds](https://github.com/Alex313031/thorium-win7/releases)

**Comment by couleurm** [comment]
ohh just realized it's under links, would be more intuitive to separate download/releases links from other resources 👍👍

**Comment by gz83** [comment]
thanks for your advice

@couleurm
