### ISSUE TITLE
Github/Source Link

### ISSUE THREAD

**Issue by ShalokShalom** [Alex313031/Alex313031.github.io#13]
Hey 

I wonder if you want a link to the Github repo. 
As of now, I was uncertain if Thorium is even open source. 
I suggest linking to https://github.com/Alex313031/Thorium

Thanks a lot

**Comment by gz83** [comment]
The thorium.rocks page already has the URL of thorium's repo

**Comment by ShalokShalom** [comment]
Then its very well hidden.

**Comment by gz83** [comment]
![image](https://github.com/Alex313031/Alex313031.github.io/assets/17492865/a003ffe9-283a-4627-8417-3c106cc52b75)

**Comment by Alex313031** [comment]
@gz83 @ShalokShalom Recently added a better link at the top of that list explicitly stating it is the link to the source repo.
