### ISSUE TITLE
Windows 7 Extended Core ?

### ISSUE THREAD

**Issue by gunir** [Alex313031/Alex313031.github.io#19]
Originally: https://msfn.org/board/topic/183465-windows-7-extended-kernel/

Repo: https://github.com/vxiiduu/VxKex

But the author disappeared, Alex you should fork it and make a Windows 7 Extended Core because we need it, current world situation stopped Windows 7 enthusiasts from making Extended Core, so we need to start it somewhere instead of forgetting about it, Vista got a great Extended Core too and it's much smaller than 7.

**Comment by Alex313031** [comment]
@gunir I will look at it. Me and @win32ss and @blackwingcat and @Feodor2 are trying to keep the dream alive.

The dream of using 2000, XP, Vista, 7, 8, and 8.1 indefinitely.

**Comment by gunir** [comment]
> @gunir I will look at it. Me and @win32ss and @blackwingcat and @Feodor2 are trying to keep the dream alive.
> 
> The dream of using 2000, XP, Vista, 7, 8, and 8.1 indefinitely.

The dream is no longer far fetched, someone is working on Windows 7 Extended Kernel, with proof-of-work:
https://msfn.org/board/topic/184971-wip-windows-7-extended-kernel/

You might want to join their project tho, very promising and it's literally the future of Windows 7.
