### ISSUE TITLE
Chromium History Comics on mobile is cut off 

### ISSUE THREAD

**Issue by ShalokShalom** [Alex313031/Alex313031.github.io#20]
See for yourself

![Screenshot_2024-01-05-10-00-01-578_com brave browser](https://github.com/Alex313031/Alex313031.github.io/assets/6344099/0cf8b6bc-5b0d-47a0-bb8b-0a9675154f99)

**Comment by Alex313031** [comment]
@ShalokShalom This is a known issue. I'm too terrible at CSS to fix it. Perhaps @midzer can help?

**Comment by midzer** [comment]
I'm gonna have a looksie.

IMHO, what I remember, the site needs a general CSS refactoring, inline CSS all over the place, but thats just my point of view...
