### ISSUE TITLE
Separate repos for separate projects / sites 

### ISSUE THREAD

**Issue by conorbone** [Alex313031/Alex313031.github.io#21]
Hey, I just wanted to highlight that you can split off the various sites that are in your GitHub pages repo to different repos and avoid cross contamination, 

https://deanattali.com/blog/multiple-github-pages-domains/

should be easier to manage the thorium site if the other included sites are in different repos.

keep up the great work <3

**Comment by Alex313031** [comment]
@conorbone I considered this, but decided against it.
