### ISSUE TITLE
Improved homepage with various builds

### ISSUE THREAD

**Issue by pritkr** [Alex313031/Alex313031.github.io#8]
As thorium has many builds - thorium(Linux), thorium-windows, SSE3 edition(Linux+ windows), AVX2 edition (Linux+ windows),mac+m1 edition, RaspberryPi build, Android build, Mercury(firefox fork),Windows 7 and arm build etc.
It would be helpful to give guidance to download and install, It would also be helpful if website detected browser's operating system and CPU to provide download recommendation and if that is not possible a beginner friendly lowest common denominator download and easy details on other builds would be helpful
Thanks

**Comment by gz83** [comment]
Thanks for the advice.

@pritkr

**Comment by Alex313031** [comment]
@pritkr Should definitely do this.
